Repository moyeobwa/moyeobwa, pull requests merged in 2024-06, with the labels that each got.

#80 feat: 모임 일정 UI 구현 및 모임 채팅 화면 디자인 변경
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/components/Button.css
  frontend/app/src/components/Calendar/Calendar.css
  frontend/app/src/components/Calendar/Calendar.jsx
  frontend/app/src/components/Calendar/Components/CalendarBox.css
  frontend/app/src/components/Calendar/Components/CalendarBox.jsx
  frontend/app/src/components/Calendar/Components/ColorRadio.css
  frontend/app/src/components/Calendar/Components/ColorRadio.jsx
  frontend/app/src/components/Calendar/Components/Schedule.css
  frontend/app/src/components/Calendar/Components/Schedule.jsx
  frontend/app/src/components/Calendar/Components/TodoAddModal.css
  frontend/app/src/components/Calendar/Components/TodoAddModal.jsx
  frontend/app/src/components/Calendar/Components/TodoDetail.css
  frontend/app/src/components/Calendar/Components/TodoDetail.jsx
  frontend/app/src/components/Calendar/Components/TodoEdit.css
  frontend/app/src/components/Calendar/Components/TodoEdit.jsx
  frontend/app/src/components/Calendar/Components/TodoItem.css
  frontend/app/src/components/Calendar/Components/TodoItem.jsx
  frontend/app/src/components/Chat.css
  frontend/app/src/components/Chat.jsx
  frontend/app/src/components/Sidebar.css
  frontend/app/src/components/Sidebar.jsx
  frontend/app/src/components/Vote.css
  frontend/app/src/components/Vote.jsx
  frontend/app/src/index.css
  frontend/app/src/pages/Gathering.css
  frontend/app/src/pages/Gathering.jsx
Labels: feat, FE, env, refactor

#77 feat: 친구 목록 및 친구 신청 UI
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/components/Button.css
  frontend/app/src/components/Friend.css
  frontend/app/src/components/Friend.jsx
  frontend/app/src/components/MyGatheringList.css
  frontend/app/src/components/UserSidebar.css
  frontend/app/src/components/UserSidebar.jsx
Labels: feat, FE

#83 feat: 프런트, 백엔드 서버 분리
  frontend/app/nginx_dev.conf
  frontend/app/package.json
  frontend/app/src/pages/LoginResponse.jsx
  frontend/app/vite.config.js
Labels: FE, env, INFRA

#89 feat: 투표 기능 구현
  backend/src/main/java/momo/app/chat/infrastructure/ChatMessageRepositoryCustom.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatMessageRepositoryImpl.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatRoomRepositoryCustom.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatRoomRepositoryImpl.java
  backend/src/main/java/momo/app/chat/service/ChatMessageCommandService.java
  backend/src/main/java/momo/app/chat/service/ChatMessageQueryService.java
  backend/src/main/java/momo/app/config/SecurityConfig.java
  backend/src/main/java/momo/app/gathering/domain/Gathering.java
  backend/src/main/java/momo/app/gathering/domain/GatheringRepository.java
  backend/src/main/java/momo/app/gathering/exception/GatheringErrorCode.java
  backend/src/main/java/momo/app/gathering/infrastructure/GatheringRepositoryCustom.java
  backend/src/main/java/momo/app/gathering/infrastructure/GatheringRepositoryImpl.java
  backend/src/main/java/momo/app/user/domain/User.java
  backend/src/main/java/momo/app/vote/controller/OptionController.java
  backend/src/main/java/momo/app/vote/controller/VoteController.java
  backend/src/main/java/momo/app/vote/domain/Option.java
  backend/src/main/java/momo/app/vote/domain/OptionRepository.java
  backend/src/main/java/momo/app/vote/domain/Vote.java
  backend/src/main/java/momo/app/vote/domain/VoteRepository.java
  backend/src/main/java/momo/app/vote/domain/VoteStatus.java
  backend/src/main/java/momo/app/vote/dto/OptionResponse.java
  backend/src/main/java/momo/app/vote/dto/VoteCreateRequest.java
  backend/src/main/java/momo/app/vote/dto/VoteRequest.java
  backend/src/main/java/momo/app/vote/dto/VoteResponse.java
  backend/src/main/java/momo/app/vote/exception/OptionErrorCode.java
  backend/src/main/java/momo/app/vote/exception/VoteErrorCode.java
  backend/src/main/java/momo/app/vote/infrastructure/OptionRepositoryCustom.java
  backend/src/main/java/momo/app/vote/infrastructure/OptionRepositoryImpl.java
  backend/src/main/java/momo/app/vote/service/OptionQueryService.java
  backend/src/main/java/momo/app/vote/service/VoteCommandService.java
  backend/src/main/java/momo/app/vote/service/VoteQueryService.java
  backend/src/test/java/momo/app/DatabaseCleanup.java
  backend/src/test/java/momo/app/gathering/infrastructure/GatheringRepositoryImplTest.java
  backend/src/test/java/momo/app/vote/infrastructure/OptionRepositoryImplTest.java
  backend/src/test/java/momo/app/vote/service/VoteCommandServiceTest.java
Labels: feat, BE

#93 Feat/#86
  backend/src/main/java/momo/app/chat/controller/ChatController.java
  backend/src/main/java/momo/app/chat/service/ChatMessageCommandService.java
  backend/src/main/java/momo/app/chat/service/ChatMessageQueryService.java
  backend/src/main/java/momo/app/config/WebSocketChannelInterceptor.java
  backend/src/main/java/momo/app/config/WebSocketConfig.java
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/components/Button.css
  frontend/app/src/components/Calendar/Components/CalendarBox.css
  frontend/app/src/components/Chat.css
  frontend/app/src/components/Chat.jsx
  frontend/app/src/components/Messages.jsx
  frontend/app/src/index.css
  frontend/app/src/pages/Gathering.jsx
  frontend/app/src/pages/Home.jsx
  frontend/app/src/router.jsx
Labels: feat, BE, FE

#94 feat: 로그인된 사용자만 접근하도록 접근 제어
  backend/src/main/java/momo/app/auth/dto/AuthUser.java
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginSuccessHandler.java
  backend/src/main/java/momo/app/user/controller/LoginController.java
  backend/src/main/java/momo/app/user/service/UserService.java
  frontend/app/src/components/PrivateRoute.jsx
  frontend/app/src/pages/Login.jsx
  frontend/app/src/pages/LoginResponse.css
  frontend/app/src/pages/LoginResponse.jsx
  frontend/app/src/pages/SignUp.jsx
  frontend/app/src/router.css
  frontend/app/src/router.jsx
Labels: feat, BE, FE

#98 feat: 모임 생성 서버 연동
  backend/src/main/java/momo/app/config/SecurityConfig.java
  frontend/app/src/components/Gathering/Editor.css
  frontend/app/src/components/Gathering/Editor.jsx
Labels: feat, FE, env

#102 feat: 친구 기능 API 구현 및 로직 수정
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginSuccessHandler.java
  backend/src/main/java/momo/app/friend/controller/FriendController.java
  backend/src/main/java/momo/app/friend/domain/Friend.java
  backend/src/main/java/momo/app/friend/domain/FriendRepository.java
  backend/src/main/java/momo/app/friend/dto/FriendResponse.java
  backend/src/main/java/momo/app/friend/exception/FriendErrorCode.java
  backend/src/main/java/momo/app/friend/service/FriendService.java
  backend/src/main/java/momo/app/user/controller/UserController.java
  backend/src/main/java/momo/app/user/domain/UserRepository.java
  backend/src/main/java/momo/app/user/dto/request/UserNicknameRequest.java
  backend/src/main/java/momo/app/user/dto/response/UserResponse.java
  backend/src/main/java/momo/app/user/service/UserService.java
  frontend/app/.gitignore
  frontend/app/Dockerfile
  frontend/app/src/components/Friend.css
  frontend/app/src/components/Friend.jsx
  frontend/app/src/pages/Login.jsx
  frontend/app/src/pages/LoginResponse.jsx
  frontend/app/src/pages/SignUp.jsx
Labels: feat, BE, FE

#105 feat: 투표 페이지 구현, 서버 연동
  backend/src/main/java/momo/app/vote/domain/Vote.java
  backend/src/main/java/momo/app/vote/domain/VoteRepository.java
  backend/src/main/java/momo/app/vote/dto/VoteResponse.java
  backend/src/main/java/momo/app/vote/infrastructure/VoteRepositoryCustom.java
  backend/src/main/java/momo/app/vote/infrastructure/VoteRepositoryImpl.java
  backend/src/main/java/momo/app/vote/service/VoteQueryService.java
  frontend/app/src/components/Vote.css
  frontend/app/src/components/Vote.jsx
  frontend/app/src/components/VoteModal.css
  frontend/app/src/components/VoteModal.jsx
  frontend/app/src/components/VoteOptionsModal.css
  frontend/app/src/components/VoteOptionsModal.jsx
  frontend/app/src/pages/Gathering.jsx
Labels: feat, FE

#106 feat: 일정 기능 구현
  backend/src/main/java/momo/app/gathering/domain/Gathering.java
  backend/src/main/java/momo/app/schedule/controller/ScheduleController.java
  backend/src/main/java/momo/app/schedule/domain/Color.java
  backend/src/main/java/momo/app/schedule/domain/Schedule.java
  backend/src/main/java/momo/app/schedule/domain/ScheduleRepository.java
  backend/src/main/java/momo/app/schedule/dto/request/ScheduleCreateRequest.java
  backend/src/main/java/momo/app/schedule/dto/request/ScheduleUpdateRequest.java
  backend/src/main/java/momo/app/schedule/dto/response/ScheduleResponse.java
  backend/src/main/java/momo/app/schedule/exception/ScheduleErrorCode.java
  backend/src/main/java/momo/app/schedule/service/ScheduleService.java
  backend/src/main/java/momo/app/user/domain/User.java
  backend/src/test/java/momo/app/friend/service/FriendServiceTest.java
Labels: feat, BE

#109 feat: 일정 기능 API 구현
  backend/src/main/java/momo/app/schedule/controller/ScheduleController.java
  backend/src/main/java/momo/app/schedule/domain/Color.java
  backend/src/main/java/momo/app/schedule/domain/ScheduleRepository.java
  backend/src/main/java/momo/app/schedule/dto/response/ScheduleResponse.java
  backend/src/main/java/momo/app/schedule/service/ScheduleService.java
  frontend/app/src/components/Calendar/Calendar.jsx
  frontend/app/src/components/Calendar/Components/CalendarBox.jsx
  frontend/app/src/components/Calendar/Components/Schedule.jsx
  frontend/app/src/components/Calendar/Components/TodoAddModal.css
  frontend/app/src/components/Calendar/Components/TodoAddModal.jsx
  frontend/app/src/components/Calendar/Components/TodoDetail.jsx
  frontend/app/src/components/Calendar/Components/TodoEdit.jsx
  frontend/app/src/components/Calendar/Components/TodoItem.jsx
  frontend/app/src/components/Chat.jsx
  frontend/app/src/components/Gathering/Editor.jsx
  frontend/app/src/pages/Gathering.jsx
Labels: feat, BE, FE

#111 feat: 중복 투표 검증 로직 작성
  backend/src/main/java/momo/app/gathering/domain/Gathering.java
  backend/src/main/java/momo/app/vote/domain/UserOption.java
  backend/src/main/java/momo/app/vote/domain/UserOptionRepository.java
  backend/src/main/java/momo/app/vote/exception/VoteErrorCode.java
  backend/src/main/java/momo/app/vote/infrastructure/UserOptionRepositoryCustom.java
  backend/src/main/java/momo/app/vote/infrastructure/UserOptionRepositoryImpl.java
  backend/src/main/java/momo/app/vote/service/VoteCommandService.java
Labels: feat, BE

#116 fix: 모임 기본 이미지 설정
  backend/src/main/java/momo/app/gathering/controller/GatheringController.java
  backend/src/main/java/momo/app/gathering/domain/Gathering.java
  backend/src/main/java/momo/app/gathering/service/GatheringCommandService.java
  backend/src/test/java/momo/app/vote/service/VoteCommandServiceTest.java
Labels: feat, BE
