Repository moyeobwa/moyeobwa, pull requests merged in 2024-05, with the labels that each got.

#51 feat: 공통 컴포넌트 부분 구현과 로그인, 회원가입 페이지 UI
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/assets/google.png
  frontend/app/src/assets/moyeobwa.png
  frontend/app/src/components/Button.css
  frontend/app/src/components/Button.jsx
  frontend/app/src/components/Header.css
  frontend/app/src/components/Header.jsx
  frontend/app/src/index.css
  frontend/app/src/pages/Home.jsx
  frontend/app/src/pages/Login.css
  frontend/app/src/pages/Login.jsx
  frontend/app/src/pages/SignUp.css
  frontend/app/src/pages/SignUp.jsx
  frontend/app/src/router.jsx
Labels: feat, FE

#52 feat: 모임 생성 페이지 UI 구현
  frontend/app/src/App.jsx
  frontend/app/src/components/Gathering/Editor.css
  frontend/app/src/components/Gathering/Editor.jsx
  frontend/app/src/context/GroupContext.jsx
  frontend/app/src/pages/Gathering.jsx
  frontend/app/src/pages/NewGathering.jsx
  frontend/app/src/router.jsx
Labels: feat, FE

#50 fix: 토큰이 없을 때 스트림 작동이 되지 않는 문제 해결
  backend/src/main/java/momo/app/auth/jwt/service/JwtExtractService.java
Labels: bug, BE

#49 chore: gitignore 설정
  .gitignore
  .gitignore.txt
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: FE, env

#57 feat: 모임방 UI 구현
  frontend/app/src/components/Chat.css
  frontend/app/src/components/Chat.jsx
  frontend/app/src/components/Messages.jsx
  frontend/app/src/components/Sidebar.css
  frontend/app/src/components/Sidebar.jsx
  frontend/app/src/pages/Gathering.css
  frontend/app/src/pages/Gathering.jsx
Labels: feat, FE

#62 feat: 모임 채팅 기능 구현
  backend/build.gradle
  backend/src/main/java/momo/app/application/controller/ApplicationController.java
  backend/src/main/java/momo/app/application/domain/Application.java
  backend/src/main/java/momo/app/application/domain/ApplicationRepository.java
  backend/src/main/java/momo/app/application/domain/ApplicationStatus.java
  backend/src/main/java/momo/app/application/dto/ApplicationCreateRequest.java
  backend/src/main/java/momo/app/application/exception/ApplicationErrorCode.java
  backend/src/main/java/momo/app/application/service/ApplicationCommandService.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtExtractService.java
  backend/src/main/java/momo/app/chat/controller/ChatController.java
  backend/src/main/java/momo/app/chat/domain/chatmessage/ChatMessage.java
  backend/src/main/java/momo/app/chat/domain/chatmessage/ChatMessageRepository.java
  backend/src/main/java/momo/app/chat/domain/chatroom/ChatRoom.java
  backend/src/main/java/momo/app/chat/domain/chatroom/ChatRoomRepository.java
  backend/src/main/java/momo/app/chat/domain/chatroom/ChatRoomUser.java
  backend/src/main/java/momo/app/chat/domain/chatroom/ChatRoomUserRepository.java
  backend/src/main/java/momo/app/chat/dto/request/ChatMessageSendRequest.java
  backend/src/main/java/momo/app/chat/dto/response/ChatMessageResponse.java
  backend/src/main/java/momo/app/chat/exception/ChatErrorCode.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatMessageRepositoryCustom.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatMessageRepositoryImpl.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatRoomRepositoryCustom.java
  backend/src/main/java/momo/app/chat/infrastructure/ChatRoomRepositoryImpl.java
  backend/src/main/java/momo/app/chat/service/ChatMessageCommandService.java
  backend/src/main/java/momo/app/chat/service/ChatMessageQueryService.java
  backend/src/main/java/momo/app/common/dto/SliceResponse.java
  backend/src/main/java/momo/app/config/QuerydslConfig.java
  backend/src/main/java/momo/app/config/SecurityConfig.java
  backend/src/main/java/momo/app/config/WebSocketConfig.java
  backend/src/main/java/momo/app/gathering/controller/GatheringController.java
  backend/src/main/java/momo/app/gathering/domain/Gathering.java
  backend/src/main/java/momo/app/gathering/exception/GatheringErrorCode.java
  backend/src/main/java/momo/app/gathering/service/GatheringCommandService.java
Labels: bug, feat, BE, env

#58 feat: 친구추가 기능 구현
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginSuccessHandler.java
  backend/src/main/java/momo/app/friend/controller/FriendController.java
  backend/src/main/java/momo/app/friend/domain/Friend.java
  backend/src/main/java/momo/app/friend/domain/FriendRepository.java
  backend/src/main/java/momo/app/friend/domain/FriendState.java
  backend/src/main/java/momo/app/friend/dto/FriendResponse.java
  backend/src/main/java/momo/app/friend/exception/FriendErrorCode.java
  backend/src/main/java/momo/app/friend/service/FriendService.java
  backend/src/main/java/momo/app/user/domain/User.java
  backend/src/main/java/momo/app/user/exception/UserErrorCode.java
  backend/src/test/java/momo/app/AppApplicationTests.java
  backend/src/test/java/momo/app/friend/service/FriendServiceTest.java
Labels: feat, BE, test

#67 feat: 메인 페이지 UI 구현
  frontend/app/src/assets/profile.png
  frontend/app/src/components/Card.css
  frontend/app/src/components/Card.jsx
  frontend/app/src/components/Header.css
  frontend/app/src/components/MyGatheringList.css
  frontend/app/src/components/MyGatheringList.jsx
  frontend/app/src/components/Profile.css
  frontend/app/src/components/Profile.jsx
  frontend/app/src/components/Radio.css
  frontend/app/src/components/Radio.jsx
  frontend/app/src/components/UserSidebar.css
  frontend/app/src/components/UserSidebar.jsx
  frontend/app/src/pages/Gathering.css
  frontend/app/src/pages/Home.css
  frontend/app/src/pages/Home.jsx
Labels: feat, FE

#69 refactor: 모임 초대, 승인 기능 제거
  backend/src/main/java/momo/app/application/controller/ApplicationController.java
  backend/src/main/java/momo/app/application/domain/Application.java
  backend/src/main/java/momo/app/application/domain/ApplicationRepository.java
  backend/src/main/java/momo/app/application/domain/ApplicationStatus.java
  backend/src/main/java/momo/app/application/dto/ApplicationCreateRequest.java
  backend/src/main/java/momo/app/application/exception/ApplicationErrorCode.java
  backend/src/main/java/momo/app/application/service/ApplicationCommandService.java
Labels: BE, refactor

#70 feat: https 설정
  Dockerfile
  backend/src/main/java/momo/app/config/SecurityConfig.java
  docker-compose.yml
  frontend/app/Dockerfile
  frontend/app/nginx_dev.conf
  nginx_dev.conf
  nginx_temp.conf
Labels: feat, BE, env
