Repository moyeobwa/moyeobwa, pull requests merged in 2024-04, with the labels that each got.

#3 docs: Issue, PR template 설정
  .github/issue_template.md
  .github/pull_request_template.md
Labels: env, docs

#5 faet: Spring 프로젝트 세팅 (#4)
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/momo/app/AppApplication.java
  backend/src/test/java/momo/app/AppApplicationTests.java
Labels: feat, BE, env

#7 feat: BE CICD 구축 (#6)
  .github/workflows/be-ci-dev.yml
  .github/workflows/be-cicd-dev.yml
Labels: feat, BE, env

#9 feat: s3 이미지 업로드, 삭제 기능
  .github/workflows/be-ci-dev.yml
  .github/workflows/be-cicd-dev.yml
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/java/momo/app/config/S3Config.java
  backend/src/main/java/momo/app/image/FileExtension.java
  backend/src/main/java/momo/app/image/S3Service.java
Labels: feat, BE

#12 fix: ssh 접속 키 변경
  .github/workflows/be-cicd-dev.yml
Labels: bug, BE

#14 Feat: 소셜 로그인 구현
  backend/build.gradle
  backend/src/main/java/momo/app/AppApplication.java
  backend/src/main/java/momo/app/auth/dto/AuthUser.java
  backend/src/main/java/momo/app/auth/jwt/JwtAccessDeniedHandler.java
  backend/src/main/java/momo/app/auth/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/momo/app/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtCreateAndUpdateService.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtExtractService.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtSendService.java
  backend/src/main/java/momo/app/auth/oauth2/CustomOAuth2User.java
  backend/src/main/java/momo/app/auth/oauth2/OAuthAttribute.java
  backend/src/main/java/momo/app/auth/oauth2/dto/GoogleResponse.java
  backend/src/main/java/momo/app/auth/oauth2/dto/OAuth2Response.java
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginFailureHandler.java
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginSuccessHandler.java
  backend/src/main/java/momo/app/auth/oauth2/service/CustomOAuth2UserService.java
  backend/src/main/java/momo/app/auth/oauth2/userInfo/GoogleOAuth2UserInfo.java
  backend/src/main/java/momo/app/common/domain/BaseTime.java
  backend/src/main/java/momo/app/config/SecurityConfig.java
  backend/src/main/java/momo/app/user/controller/LoginController.java
  backend/src/main/java/momo/app/user/domain/Role.java
  backend/src/main/java/momo/app/user/domain/User.java
  backend/src/main/java/momo/app/user/domain/UserRepository.java
  backend/src/main/java/momo/app/user/dto/request/UserSignupJsonRequest.java
  backend/src/main/java/momo/app/user/dto/request/UserSignupRequest.java
  backend/src/main/java/momo/app/user/service/UserService.java
Labels: feat, BE

#20 feat: 기본적인 모임 Command api 구현
  backend/src/main/java/momo/app/config/SecurityConfig.java
  backend/src/main/java/momo/app/gathering/controller/GatheringController.java
  backend/src/main/java/momo/app/gathering/domain/Category.java
  backend/src/main/java/momo/app/gathering/domain/Gathering.java
  backend/src/main/java/momo/app/gathering/domain/GatheringInfo.java
  backend/src/main/java/momo/app/gathering/domain/GatheringMember.java
  backend/src/main/java/momo/app/gathering/domain/GatheringMemberRepository.java
  backend/src/main/java/momo/app/gathering/domain/GatheringRepository.java
  backend/src/main/java/momo/app/gathering/domain/GatheringTag.java
  backend/src/main/java/momo/app/gathering/domain/GatheringTagRepository.java
  backend/src/main/java/momo/app/gathering/dto/GatheringCreateJsonRequest.java
  backend/src/main/java/momo/app/gathering/dto/GatheringCreateRequest.java
  backend/src/main/java/momo/app/gathering/dto/GatheringUpdateJsonRequest.java
  backend/src/main/java/momo/app/gathering/dto/GatheringUpdateRequest.java
  backend/src/main/java/momo/app/gathering/service/GatheringCommandService.java
  backend/src/main/java/momo/app/tag/domain/Tag.java
  backend/src/main/java/momo/app/tag/domain/TagRepository.java
Labels: feat, BE

#23 feat: swagger-ui 설정
  backend/build.gradle
  backend/src/main/java/momo/app/config/SecurityConfig.java
  backend/src/main/java/momo/app/config/SwaggerConfig.java
Labels: BE, env

#22 feat: 테스트용 토큰 발급 api 구현
  backend/src/main/java/momo/app/auth/controller/TestTokenController.java
  backend/src/main/java/momo/app/config/SecurityConfig.java
Labels: BE, env

#24 feat: GlobalExceptionHandler 구현
  backend/src/main/java/momo/app/common/error/ErrorCode.java
  backend/src/main/java/momo/app/common/error/GlobalExceptionHandler.java
  backend/src/main/java/momo/app/common/error/dto/ErrorResponse.java
  backend/src/main/java/momo/app/common/error/exception/BusinessException.java
Labels: feat, BE, env

#26 feat: 로그아웃 기능 구현
  backend/src/main/java/momo/app/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtCreateAndUpdateService.java
  backend/src/main/java/momo/app/common/util/RedisUtil.java
  backend/src/main/java/momo/app/config/RedisConfig.java
  backend/src/main/java/momo/app/user/controller/LoginController.java
  backend/src/main/java/momo/app/user/domain/User.java
  backend/src/main/java/momo/app/user/service/UserService.java
Labels: feat, BE

#25 feat: Redis 설정
  backend/build.gradle
  backend/src/main/java/momo/app/auth/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtCreateAndUpdateService.java
  backend/src/main/java/momo/app/common/util/RedisUtil.java
  backend/src/main/java/momo/app/config/RedisConfig.java
  backend/src/main/java/momo/app/user/controller/LoginController.java
  backend/src/main/java/momo/app/user/domain/User.java
  backend/src/main/java/momo/app/user/service/UserService.java
Labels: feat, BE, env

#34 Feat/#32
  frontend/meeting/.gitignore.txt
  frontend/meeting/package-lock.json
  frontend/meeting/package.json
Labels: FE, env

#37 feat: 소셜로그인 기능 수정 및 클라이언트 페이지 Redirect
  backend/src/main/java/momo/app/auth/jwt/service/JwtExtractService.java
  backend/src/main/java/momo/app/auth/jwt/service/JwtSendService.java
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginSuccessHandler.java
  backend/src/main/java/momo/app/user/controller/LoginController.java
  backend/src/main/java/momo/app/user/service/UserService.java
Labels: feat, BE

#38 feat: 소셜 로그인 오류 수정
  backend/src/main/java/momo/app/auth/jwt/service/JwtExtractService.java
  backend/src/main/java/momo/app/auth/oauth2/handler/LoginSuccessHandler.java
  backend/src/main/java/momo/app/config/SecurityConfig.java
Labels: bug, BE

#39 feat: 쿠키 생성 코드 변경
  backend/src/main/java/momo/app/auth/jwt/service/JwtSendService.java
Labels: feat, BE
